
import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";
import { Sparkles, Image as ImageIcon, RefreshCcw } from 'lucide-react';

export const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('A cyberpunk banana riding a skateboard');
  const [image, setImage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generateImage = async () => {
    if (!prompt.trim()) return;

    setLoading(true);
    setError(null);
    setImage(null);

    try {
      // Access API key from process.env (injected by the environment)
      const apiKey = process.env.API_KEY;
      if (!apiKey) {
        throw new Error("API Key is missing. Please ensure you are logged in.");
      }

      const ai = new GoogleGenAI({ apiKey });
      
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: prompt }]
        }
      });

      let foundImage = false;
      
      if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            const base64EncodeString: string = part.inlineData.data;
            const imageUrl = `data:${part.inlineData.mimeType};base64,${base64EncodeString}`;
            setImage(imageUrl);
            foundImage = true;
            break;
          }
        }
      }

      if (!foundImage) {
        throw new Error("No image generated by the model. Try a different prompt.");
      }

    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to generate image");
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
        generateImage();
    }
  };

  return (
    <div className="border-2 border-os-border bg-os-bg p-4 shadow-[4px_4px_0_0_var(--os-border)] mt-6 mb-8">
      <div className="flex items-center gap-2 mb-3 border-b-2 border-dashed border-os-border pb-2">
        <Sparkles size={16} className="text-os-accent" />
        <span className="font-bold text-xs tracking-wider text-os-text">IMAGEN_TOOL.EXE [NANO_BANANA_CORE]</span>
      </div>

      <div className="flex flex-col md:flex-row gap-2 mb-4">
        <div className="flex-1 border-2 border-os-border bg-os-window focus-within:border-os-accent transition-colors relative text-os-text">
            <input 
                type="text" 
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyDown={handleKeyDown}
                className="w-full h-10 px-3 bg-transparent outline-none font-mono text-sm placeholder:text-os-muted"
                placeholder="Enter prompt..."
                disabled={loading}
            />
            <div className="absolute right-2 top-1/2 -translate-y-1/2 opacity-30 pointer-events-none">
                <ImageIcon size={16} />
            </div>
        </div>
        <button 
            onClick={generateImage}
            disabled={loading}
            className={`
                h-10 px-6 font-bold border-2 border-os-border flex items-center justify-center gap-2 shadow-[2px_2px_0_0_var(--os-border)] transition-all
                ${loading ? 'bg-os-muted cursor-not-allowed text-os-text' : 'bg-os-accent hover:translate-y-[-1px] hover:shadow-[3px_3px_0_0_var(--os-border)] active:translate-y-[1px] active:shadow-[1px_1px_0_0_var(--os-border)] text-white'}
            `}
        >
            {loading ? <RefreshCcw className="animate-spin" size={16}/> : 'RENDER'}
        </button>
      </div>

      <div className="w-full aspect-square md:aspect-video min-h-[200px] bg-os-window border-2 border-os-border relative overflow-hidden flex items-center justify-center">
          {/* Grid Background */}
          <div className="absolute inset-0 opacity-10 pointer-events-none" 
               style={{ backgroundImage: 'linear-gradient(var(--os-text) 1px, transparent 1px), linear-gradient(90deg, var(--os-text) 1px, transparent 1px)', backgroundSize: '20px 20px' }} 
          />

          {loading && (
             <div className="flex flex-col items-center gap-2 z-10 animate-pulse text-os-text">
                <div className="w-12 h-12 border-4 border-t-os-accent border-r-os-accent border-b-transparent border-l-transparent rounded-full animate-spin" />
                <span className="font-mono font-bold text-xs mt-2">PROCESSING...</span>
             </div>
          )}

          {!loading && !image && !error && (
              <div className="text-center p-6 text-os-muted z-10">
                  <p className="font-bold mb-1">NO INPUT DETECTED</p>
                  <p className="text-xs">Enter a prompt to initialize generation.</p>
              </div>
          )}

          {error && (
               <div className="text-center p-6 text-red-600 bg-red-50 border border-red-200 z-10 max-w-[90%]">
                 <p className="font-bold text-sm mb-1">SYSTEM ERROR</p>
                 <p className="text-xs font-mono">{error}</p>
               </div>
          )}

          {image && !loading && (
              <img 
                src={image} 
                alt="Generated output" 
                className="w-full h-full object-contain bg-black"
              />
          )}
      </div>
      
      <div className="mt-2 flex justify-between text-[10px] font-mono text-os-muted">
          <span>STATUS: {loading ? 'BUSY' : 'IDLE'}</span>
          <span>MODEL: gemini-2.5-flash-image</span>
      </div>
    </div>
  );
};
