/**
 * Gruvbox-inspired syntax highlighting theme for Prism / SyntaxHighlighter.
 */
export const gruvboxTheme: Record<string, React.CSSProperties> = {
    'code[class*="language-"]': {
        color: '#ebdbb2',
        fontFamily: '"Courier Prime", monospace',
        fontSize: '13px',
        lineHeight: '1.6',
        direction: 'ltr',
        textAlign: 'left',
        whiteSpace: 'pre',
        wordSpacing: 'normal',
        wordBreak: 'normal',
        MozTabSize: '4',
        OTabSize: '4',
        tabSize: '4',
        WebkitHyphens: 'none',
        MozHyphens: 'none',
        msHyphens: 'none',
        hyphens: 'none',
    },
    'pre[class*="language-"]': {
        color: '#ebdbb2',
        fontFamily: '"Courier Prime", monospace',
        fontSize: '13px',
        lineHeight: '1.6',
        direction: 'ltr',
        textAlign: 'left',
        whiteSpace: 'pre',
        wordSpacing: 'normal',
        wordBreak: 'normal',
        MozTabSize: '4',
        OTabSize: '4',
        tabSize: '4',
        WebkitHyphens: 'none',
        MozHyphens: 'none',
        msHyphens: 'none',
        hyphens: 'none',
        padding: '20px',
        margin: '0',
        overflow: 'auto',
        background: 'transparent',
    },
    comment: { color: '#928374', fontStyle: 'italic' },
    prolog: { color: '#928374' },
    doctype: { color: '#928374' },
    cdata: { color: '#928374' },
    punctuation: { color: '#a89984' },
    namespace: { opacity: 0.7 },
    property: { color: '#fb4934' },
    keyword: { color: '#fb4934' },
    tag: { color: '#fb4934' },
    'class-name': { color: '#fabd2f' },
    boolean: { color: '#d3869b' },
    constant: { color: '#d3869b' },
    symbol: { color: '#fe8019' },
    deleted: { color: '#fb4934' },
    number: { color: '#d3869b' },
    selector: { color: '#b8bb26' },
    'attr-name': { color: '#fabd2f' },
    string: { color: '#b8bb26' },
    char: { color: '#b8bb26' },
    builtin: { color: '#fabd2f' },
    inserted: { color: '#b8bb26' },
    variable: { color: '#83a598' },
    operator: { color: '#fe8019' },
    entity: { color: '#fabd2f', cursor: 'help' },
    url: { color: '#fabd2f' },
    'attr-value': { color: '#b8bb26' },
    function: { color: '#b8bb26' },
    regex: { color: '#fe8019' },
    important: { color: '#fe8019', fontWeight: 'bold' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
};
